#!/bin/bash

start_seq=`bash userno.sh $1 10`
let no=$start_seq+$2-1

#lsdir=`ls $1`
#dirarr=($lsdir)

export CQLSH_NO_BUNDLED=true
cassandra/bin/cqlsh "127.0.0.$no 9042"

#for subdir in ${dirarr[@]}; do
#    match=`echo "$subdir" | egrep "node(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[1-9])"`
#    if [[ $match = "$subdir" ]]; then
#        let no=${subdir:4}+$2-1
#        tdir="node$no"
#        export CQLSH_NO_BUNDLED=true
#        cassandra/bin/cqlsh "127.0.0.$no 9042"
#	break
#    fi
#done
