#!/bin/bash
start_seq=`bash userno.sh $1 10`
let no=$start_seq+$2-1
tdir="node$no"
export CASSANDRA_CONF="$1/$tdir/conf"
CLASSPATH=$CASSANDRA_CONF
#for jar in /usr/share/cassandra/lib/*.jar; do
#    CLASSPATH=$CLASSPATH:$jar
#done

for jar in cassandra/lib/*.jar; do
    CLASSPATH=$CLASSPATH:$jar
done
        
for jar in /cassandra/build/lib/jars/*.jar; do
    CLASSPATH=$CLASSPATH:$jar
done
          
CLASSPATH=$CLASSPATH:"cassandra/build/apache-cassandra-3.7-SNAPSHOT.jar"
export CLASSPATH
CASSANDRA_HOME=cassandra
# set JVM javaagent opts to avoid warnings/errors
if [ "$JVM_VENDOR" != "OpenJDK" -o "$JVM_VERSION" \> "1.6.0" ] \
      || [ "$JVM_VERSION" = "1.6.0" -a "$JVM_PATCH_VERSION" -ge 23 ]
then
    JAVA_AGENT="$JAVA_AGENT -javaagent:$CASSANDRA_HOME/lib/jamm-0.3.0.jar"
fi
export CASSANDRA_HOME
export JAVA_AGENT
export CASSANDRA_INCLUDE=`pwd`"/placeholder"
shift;
shift;
cassandra/bin/nodetool "$*"
